#!/bin/sh

varold=$(cat /home/begruget/log.log) &> /dev/null
varnew=$(cat /etc/group | grep "sudo" > /tmp/log2.log)
if [ -z "grep "sudo" /etc/group | grep ","" ]
then 
  sudoer=$(grep "sudo" /etc/group | cut -d ":" -f4)
else 	
    sudoer=$( grep "sudo" /etc/group | rev  | cut -d "," -f1 | rev)
fi
if ["$varold" -ne "$varnew"]
then 
		sendemail -f lesjacobins2017@gmail.com -t lesjacobins2017@gmail.com -s smtp.gmail.com:25 -xu lesjacobins2017@gmail.com -xp jacobin2017 -u Modification SUDOERS  -m "!!!!! les droits on changé pour $sudoer" -a /tmp/log2.log
		sudo grep "sudo" /etc/group > /tmp/log.log
else
	echo " le nombre de users avec les droits sudo est identique"
fi
